### ISSUE TITLE
Starter blog project errors

### ISSUE THREAD

**Issue by suhmeanhuck** [navneetsharmaui/sveltekit-blog#3]
I tried to use the starter project with npm and pnpm but kept running into errors so i tried yarn. For all of them when I run the run dev command I get the following error:

macuser@macusers-MacBook-Pro blog % yarn run dev
yarn run v1.22.10
$ npm run check-env && npm run dev:sveltekit

> sveltekit-blog@1.0.0 check-env
> node --loader ts-node/esm scripts/js/check-env.ts

(node:2613) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

> sveltekit-blog@1.0.0 dev:sveltekit
> svelte-kit dev

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/macuser/blog/node_modules/@sveltejs/kit/svelte-kit.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I deleted the node_modules folder and on yarn install and yarn run dev I had the following error:

macuser@macusers-MacBook-Pro blog % yarn run dev
yarn run v1.22.10
$ npm run check-env && npm run dev:sveltekit

> sveltekit-blog@1.0.0 check-env
> node --loader ts-node/esm scripts/js/check-env.ts

(node:2884) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

> sveltekit-blog@1.0.0 dev:sveltekit
> svelte-kit dev

> config.kit.ssr has been removed — use the handle hook instead: https://kit.svelte.dev/docs#hooks-handle'
    at file:///Users/macuser/blog/node_modules/@sveltejs/kit/dist/cli.js:874:10
    at file:///Users/macuser/blog/node_modules/@sveltejs/kit/dist/cli.js:766:43
    at file:///Users/macuser/blog/node_modules/@sveltejs/kit/dist/cli.js:752:18
    at file:///Users/macuser/blog/node_modules/@sveltejs/kit/dist/cli.js:752:18
    at validate_config (file:///Users/macuser/blog/node_modules/@sveltejs/kit/dist/cli.js:936:9)
    at load_config (file:///Users/macuser/blog/node_modules/@sveltejs/kit/dist/cli.js:913:20)
    at async file:///Users/macuser/blog/node_modules/@sveltejs/kit/dist/cli.js:1013:19
error Command failed with exit code 1.

**Comment by opentechexpert** [comment]
Update from "ts-node": "^10.2.1" to "ts-node": "^10.5.0". Should work.
